
export const metadata = {
  title: "My Portfolio",
  description: "Generated by ChatGPT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="font-sans bg-white dark:bg-zinc-900 text-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
